name: Daniel Stieber
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d3b77'
    - '#f2ca8c'
    - '#f07a22'
    - '#9d90a2'
    - '#735811'
  brandStrength: 0
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
